### ISSUE TITLE
Developer, read this

### ISSUE THREAD

**Issue by dxffety** [TipzTeam/MAlone#9]
Man, this app of yours has a really ugly design, why won't it actually program instead of using Sketchware? I don't want to offend but it's my opinion

**Comment by TipzTeam** [comment]
Well, this app is not completed. And it won't be completed any time soon, so that's not an issue for now. If you have any UI design to submit, send it here. Thank you.

**Comment by dxffety** [comment]
Ok...

**Comment by dxffety** [comment]
When I finish doing some projects, I'll help you with the design xD
